queue_type: sqs
queues:
  default:
    concurrency: 10
  sample01:
    concurrency: 3
    methods:
      - 'SampleA#hoge1'
      - 'SampleB.hoge2'
    classes:
      - 'ClassInvocation1'
  sample02:
    concurrency: 1
    methods:
      - 'SampleA#hoge2'
      - 'SampleB.hoge1'
sqs:
  account:
    access_key_id: 'YOUR_ACCESS_KEY_ID'
    secret_access_key: 'YOUR SECRET ACCESS KEY'
    region: 'ap-northeast-1'
